### ISSUE TITLE
Suggestions to improve installation guide

### ISSUE THREAD

**Issue by Peter-Metz** [open-source-economics/PCI#5]
While the installation process went quite smoothly once I was equipped with an appropriate machine, I have a few suggestions to clarify the installation process:

1. Consider mentioning the fact that the user needs a CUDA-enabled GPU to create the environment and run PCI. I found a list of compatible GPU's [here](https://developer.nvidia.com/cuda-gpus).
2. To install the `jieba-fast` package, I first had to install [Visual Studio C++ Build Tools](https://visualstudio.microsoft.com/downloads/#build-tools-for-visual-studio-2019). If this is necessary, it might be helpful to ask users to install these tools.
3. To get the tests to pass, I had to separately pip install `MonthDelta`. I see that `MonthDelta` is included in your `environment.yml`, so I'm not sure why it didn't install correctly the first time.
4. The tests have to be run from the `PCI-China/PCI-China` directory.

cc: @ctszkin @towashington

**Comment by ctszkin** [comment]
Peter,

Thanks for the suggestions. We included some notes about #1, #2, and #4 in
the installation guide. They should help the user to install and test our
code.

For #3, since the  MonthDelta is listed after  jieba-fast  in the
environment.yml, conda may have skipped the installation of MonthDelta.

Thanks,
Julian

**Comment by Peter-Metz** [comment]
@ctszkin Looks great! Closing this issue.
